---
name: "Chris Guiterman"
position: "Research Scientist"
address: "Laboratory of Tree-Ring Research, University of Arizona"
phone: +1 520-230-2341
www: chris-guiterman.rbind.io
email: chguiterman@arizona.edu
twitter: chris.guiterman
github: chguiterman
aboutme: ""
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  vitae::moderncv:
    theme: classic
---

```{r eval=FALSE, include=FALSE}
# Remember to spell check!!
# data_files <- list.files(here::here("data"), pattern = ".csv", full.names = TRUE)
# spelling::spell_check_files(c("CV.Rmd", data_files))
```

```{r eval=FALSE, include=FALSE}
# To update CV on my website, run the following code in the console:
# rmarkdown::render("CV.Rmd", output_file = "/Users/scottericr/Documents/Blogdown/My Website/static/files/Eric Scott cv.pdf")
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tidyverse)
library(lubridate)
library(here)
library(readxl)
library(glue)
library(conflicted)
conflict_prefer("filter", "dplyr")
conflict_prefer("here", "here")
```

```{r jobs}
jobs <- read_csv(here("data", "jobs.csv")) %>% 
   filter(!is.na(start_date)) %>% 
   mutate(Start = mdy(start_date),
         End = mdy(end_date)) %>% 
  mutate(When = case_when(
    is.na(End) ~ glue("{year(Start)}--Present") %>% as.character(),
    year(Start) == year(End) ~ year(End) %>% as.character(),
    TRUE ~ glue("{year(Start)}--{year(End)}") %>% as.character()
  )) %>% 
  mutate(End = if_else(is.na(End), today() + years(2), End)) #if no end date specified, set it to two years from now for sorting purposes, i.e. so jobs I'm still doing show up at top
```

```{r teaching}
courses <- read.csv(here("data", "teaching.csv")) %>% 
  mutate(when = glue("{semester} {year}")) %>% 
  arrange(desc(year))
```

```{r presentations, include=FALSE}
 presentations.raw <- read_csv(here("data", "presentations.csv"))
 presentations <- 
   presentations.raw %>%  
   mutate(When = mdy(When)) %>% 
   filter(When < today()) #exclude upcoming talks -->
``` 

<!-- ```{r prof-devel, include=FALSE} -->
<!-- development.raw <- read_csv(here("data", "professional development.csv")) -->
<!-- development <-  -->
<!--   development.raw %>%  -->
<!--   mutate(date = mdy(date)) -->
<!-- ``` -->

<!-- ```{r awards, include=FALSE} -->
<!-- awards.raw <- read_csv(here("data", "awards and grants.csv")) -->
<!-- awards <- awards.raw %>%  -->
<!--   mutate(date = mdy(date)) %>%  -->
<!--   arrange(desc(date)) -->
<!-- ``` -->

```{r edu, include=FALSE}
edu.raw <- read_csv(here("data", "education.csv"))
edu <-
  edu.raw %>% 
  mutate(chair = glue("Chair: {chair}"),
         dissertation = glue("\\textbf{[dissertation]}", 
                             .open = "[", .close = "]")
         ) %>% 
  gather(dissertation, chair, key = "whytype", value = "why")
edu["why"]
``` 

``` {r publications, include=FALSE}
pubs <- read_xlsx(here::here("data", "my_pubs.xlsx"))
```

# Education

```{r}
detailed_entries(edu %>% 
                    filter(whytype == "dissertation"),
                 when = end_date,
                 what = degree,
                 where = location,
                 with = glue("{university}, {department}"),
                 why = why,
                 .protect = FALSE)

```
# Experience

```{r}
jobs %>% 
  select(-why) %>% 
  arrange(desc(End)) %>% 
  filter(where != "Joseph, OR") %>% 
  detailed_entries(
    what = what,
    when = When,
    with = with,
    where = where,
    .protect = FALSE
  )

```

<!-- <!--# Teaching Interests -->
<!-- A sentence or two about the sorts of courses I'd like to teach.  Tailor to each job application -->
<!-- -->

# Courses Taught
## Lead or co-instructor
```{r}
courses %>% 
  filter(tag == "Instructor") %>% 
  detailed_entries(
    when = when,
    what = what,
    with = with,
    where = where,
    .protect = FALSE
  )
```
## Teaching assistant
```{r}
courses %>% 
  filter(tag == "TA") %>% 
  detailed_entries(
    when = when,
    what = what,
    with = with,
    where = where,
    .protect = FALSE
  )
```

# Grants

<!-- ```{r} -->
<!-- awards %>% -->
<!--   filter(tag == "grant") %>% -->
<!--   detailed_entries(what = award, when = glue("{month(date, label = TRUE)} {year(date)}"), -->
<!--                    why = amount) %>%  -->
<!--   mutate_all(as.character) %>%  -->
<!--   mutate(with = as.character(with), -->
<!--          when = as.character(when), -->
<!--          where = as.character(where)) -->
<!-- ``` -->

# Awards and Honors

<!-- ```{r} -->
<!--  awards %>%  -->
<!--   filter(!tag %in% c("failed", "travel", "grant")) %>%  -->
<!--   brief_entries(what = award, when = glue("{month(date, label = TRUE)} {year(date)}"), with = with) -->
<!-- ``` -->

# Publications

```{r} 
 pubs %>% 
   filter(type == "journal") %>%
   detailed_entries(with = author,
                    when = year,
                    what = title,
                    where = journal, 
                    .protect = FALSE)
```


## Software

<!-- ```{r} -->
<!-- df <- tribble(~what, ~when, ~with, ~where, ~why, -->
<!--               "webchem: retrieve chemical information from the web", -->
<!--               2020, -->
<!--               "E Szöcs, D Muench, J Ranke, ER Scott, J Stanstrup, R Allaway, Tamas Stirling", -->
<!--               "https://cran.r-project.org/web/packages/webchem/", -->
<!--               "Contributor and maintainer", -->

<!--               "holodeck: A tidy interface for simulating multivariate data", -->
<!--               2018, -->
<!--               "ER Scott", -->
<!--               "https://cran.r-project.org/web/packages/holodeck/", -->
<!--               "Author and maintainer", -->

<!--               "bumbl: Tools for modeling bumblebee colony growth", -->
<!--               2019, -->
<!--               "ER Scott, E Crone", -->
<!--               "https://github.com/Aariq/bumbl", -->
<!--               "Author and maintainer" -->

<!--               ) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- df %>%  -->
<!--   arrange(desc(when)) %>%  -->
<!--   detailed_entries(what = what, when = when, with = with, where = where, why = why) -->
<!-- ``` -->


# Presentations 

## Research Talks

```{r}
presentations %>%
  filter(Tag %in% c("talk", "invited")) %>%
  arrange(desc(When)) %>%
  detailed_entries(what = Title,
                   when = glue("{month(When, label = TRUE)} {year(When)}"),
                   with = Authors,
                   where = glue("{Conference}, {Location}"), 
                   why = Why, 
                   .protect = FALSE)
```

## Posters
``` {r}
presentations %>%
  filter(Tag == "poster") %>%
  arrange(desc(When)) %>%
  detailed_entries(what = Title,
                   when = glue("{month(When, label = TRUE)} {year(When)}"),
                   with = Authors,
                   where = glue("{Conference}, {Location}"), 
                   why = Why, 
                   .protect = FALSE)
```                   

<!-- # Outreach -->

<!-- ```{r} -->
<!-- outreach %>% -->
<!--   arrange(desc(sortdate)) %>% -->
<!--   detailed_entries(when = When, -->
<!--                    what = Title, -->
<!--                    with = Organization, -->
<!--                    where = Location, -->
<!--                    why = Description) -->
<!-- ``` -->

<!-- # Service -->

<!-- **Manuscript Reviews** -->
<!-- ```{r} -->
<!-- #set this up to pull from publoons some day. -->
<!-- ``` -->

<!-- - Journal of Chemical Ecology (1) -->
<!-- - Ecological Entomology (3) -->
<!-- - International Journal of Climatology (1) -->

<!-- ```{r} -->
<!-- jobs %>% -->
<!--   filter(Tag == "service") %>%  -->
<!--   detailed_entries( -->
<!--     what = What, -->
<!--     when = When, -->
<!--     with = With, -->
<!--     where = Where, -->
<!--     why = Why -->
<!--   ) -->
<!-- ``` -->

<!-- \pagebreak -->

<!-- ## Presented Workshops -->

<!-- ```{r} -->
<!-- presentations %>%  -->
<!--   filter(Tag == "workshop") %>%  -->
<!--   arrange(desc(When)) %>%  -->
<!--   detailed_entries(what = Title, -->
<!--                    when = glue("{month(When, label = TRUE)} {year(When)}"), -->
<!--                    with = Conference, -->
<!--                    where = Location, -->
<!--                    why = Award) -->
<!-- ``` -->

<!-- # Professional Development -->

<!-- ```{r} -->
<!-- development %>%  -->
<!--   brief_entries( -->
<!--     what = title, -->
<!--     when = glue("{month(date, label = TRUE)} {year(date)}"), -->
<!--     with = location -->
<!--   ) -->
<!-- ``` -->
