
# Grants & Fellowships

```{r grants data}
grants <- read_csv(here("data", "grants.csv")) %>% 
  mutate(date = case_when(
    is.na(start_year) ~ glue("{end_year}"),
    TRUE ~ glue("{start_year}--{end_year}")
  )
  ) %>% 
  arrange(desc(end_year))
```

Total research funding: `r dollar(sum(grants$amount, na.rm=TRUE) - 500)`

*Note: I served as the project lead and/or PI unless otherwise noted.*

\vspace{12pt}

```{r submitted grants}
sub_gr <- tribble(~ date, ~ title, ~ sponsor, ~ amount, ~ collab,
                  "Submitted", "Resilience in a longleaf savanna: Historical tree recruitment in response to frequent disturbance and climate variability", "Wade Research Foundation", 75000, "Monica Rother",
                  "Submittted", "burnrData: The North American tree-ring fire history database in R", "USGS Community for Data Integration", 49964, "Ellis Margolis",
                  "In-prep (2nd round)", "Feedbacks and scale at an ancient wildland-urban interface", "NSF Dynamics of Integrated Socio-Environmental Systems", 1599949, "Chris Roos (PI). UofA (Guiterman co-PI) share $362,117."
                  )
sub_gr %>% 
    detailed_entries(
    when = date, 
    what = title,
    with = sponsor, 
    where = dollar(amount),
    # why =  ifelse(!is.na(PI), glue("{PI} (PI)"), NA)
    why = ifelse(!is.na(collab), glue("with {collab}"), NA)
  )

```

```{r awarded grants}
grants %>% 
  detailed_entries(
    when = date, 
    what = title,
    with = sponsor, 
    where = dollar(amount),
    # why =  ifelse(!is.na(PI), glue("{PI} (PI)"), NA)
    why = ifelse(!is.na(collab), glue("with {collab}"), NA)
  )
```
